version: '3.8'

services:
  app:
    build: ./php
    volumes:
      - ./php/work:/work

  web:
    build: ./nginx
    ports:
      - 80:80
    depends_on: 
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php/work:/work
    working_dir: /work

  db:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/var_lib_mysql:/var/lib/mysql